/* Generated by AN DISI Unibo */ 
package it.unibo.ponger

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Ponger ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val N = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outmagenta("$name -- Sono pronto!")
						emit("connected", "connected(Ponger)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="play",cond=whenDispatch("ping"))
				}	 
				state("play") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ping(N)"), Term.createTerm("ping(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
								 	   
								if(  payloadArg(0).toInt() < 4  
								 ){delay(200) 
								forward("pong", "pong(${payloadArg(0)})" ,"pinger" ) 
								updateResourceRep( "pong(${payloadArg(0)})"  
								)
								}
								else
								 {CommUtils.outmagenta("$name -- Ho sbagliato colpo!")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="play",cond=whenDispatch("ping"))
					transition(edgeName="t15",targetState="endgame",cond=whenEvent("end"))
				}	 
				state("endgame") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name -- Ho perso!")
						//terminate(0)
						context!!.removeInternalActor(myself)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
