/* Generated by AN DISI Unibo */ 
package it.unibo.calculator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Calculator ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("Calculator -- In avvio...")
						delay(100) 
						CommUtils.outmagenta("Calculator -- Avviato!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleJob",cond=whenRequest("dojob"))
				}	 
				state("handleJob") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dojob(N)"), Term.createTerm("dojob(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("Calculator -- Ricevuto messaggio dojob(${payloadArg(0)})")
								CommUtils.outmagenta("Calculator -- Creo attore per la gestione del messaggio")
								delegateCurrentMsgTodynamic("executor") 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="handleJob",cond=whenRequest("dojob"))
				}	 
			}
		}
} 
